server:
  port: 9091
  servlet:
    context-path: /phonebook
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: sys
    driver-class-name: oracle.jdbc.OracleDriver
